# Generated by Django 4.2.1 on 2023-05-09 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_upvote_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvote',
            name='points',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
