# Generated by Django 4.2.1 on 2023-05-09 18:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_upvote_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvote',
            name='post',
        ),
        migrations.AddField(
            model_name='upvote',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='post.post'),
            preserve_default=False,
        ),
    ]
