# Generated by Django 4.2.1 on 2023-05-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_remove_upvote_posts_upvote_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvote',
            name='points',
            field=models.IntegerField(),
        ),
    ]
