# Generated by Django 4.2.1 on 2023-05-17 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_upvote_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='upvote_count',
        ),
    ]
